// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNk8EvfCf2xIcC6XHhtJZph87RaMMIE5U',
    appId: '1:213374030610:web:6474ae8f22c3d0818bd9cb',
    messagingSenderId: '213374030610',
    projectId: 'ivms2-e8aba',
    authDomain: 'ivms2-e8aba.firebaseapp.com',
    storageBucket: 'ivms2-e8aba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojxyUm-F8_E18pE6kWANDj8mX1eB2c8E',
    appId: '1:213374030610:android:5c0c999ffa3557df8bd9cb',
    messagingSenderId: '213374030610',
    projectId: 'ivms2-e8aba',
    storageBucket: 'ivms2-e8aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmu3NXwcX50g2x_95dhal1_MxCtNWuoN4',
    appId: '1:213374030610:ios:ccb0337196b54a5b8bd9cb',
    messagingSenderId: '213374030610',
    projectId: 'ivms2-e8aba',
    storageBucket: 'ivms2-e8aba.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmu3NXwcX50g2x_95dhal1_MxCtNWuoN4',
    appId: '1:213374030610:ios:ccb0337196b54a5b8bd9cb',
    messagingSenderId: '213374030610',
    projectId: 'ivms2-e8aba',
    storageBucket: 'ivms2-e8aba.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2ZR6t7hxtGUu8-VhcNU5IR3j4XnAYvew',
    appId: '1:213374030610:web:5c2f921790e89f998bd9cb',
    messagingSenderId: '213374030610',
    projectId: 'ivms2-e8aba',
    authDomain: 'ivms2-e8aba.firebaseapp.com',
    storageBucket: 'ivms2-e8aba.firebasestorage.app',
  );

}